Repository EddieHubCommunity/open-source-practice, pull requests merged in 2022-10, with the labels that each got.

#1928 Update README.md
  README.md
Labels: small

#1935 Add maneshwar-mehra
  README.md
Labels: small

#1930 Add Vandit1604
  README.md
Labels: small

#1954 New name added
  README.md
Labels: small

#1955 Add itzrahulyadav
  README.md
Labels: small

#1961 Update README.md
  README.md
Labels: small

#1958 Add Abhijeet03s
  README.md
Labels: small

#1953 github profile link added
  README.md
Labels: small

#1952 Vedant (Readme.md updated)
  README.md
Labels: small

#1845 Update Readme to add my profile
  README.md
Labels: small

#1964 divyKS
  README.md
Labels: small

#1966 Update README.md
  README.md
Labels: small

#1965 Update README.md
  README.md
Labels: small

#1956 Updated READ.me to include my name and github profile link
  README.md
Labels: small

#1967 Add aojanzen
  README.md
Labels: small

#1946 Fix
  README.md
Labels: small

#1960 [Add] name added to Readme
  README.md
Labels: small

#1970 chore: add Tamanna-S
  README.md
Labels: small

#1917 Updated README to add my name and profile
  README.md
Labels: small

#1941 Update README.md
  README.md
Labels: small

#1915 Added my name on line 1070
  README.md
Labels: small

#1942 chore: add Jyotiraditya24
  README.md
Labels: small

#1899 chore: add chandraprakash darji
  README.md
Labels: small

#1971 created new branch and updates readme
  README.md
Labels: small

#1927 Update readme.md
  README.md
Labels: small

#1925 Add Odohofre
  README.md
Labels: small

#1924 Update README.md
  README.md
Labels: small

#1923 updateREADME.md
  README.md
Labels: small

#1921 Update README.md
  README.md
Labels: small

#1980 Add Cory to README.md
  README.md
Labels: small

#1919 Adding Name
  README.md
Labels: small

#1936 Update README.md
  README.md
Labels: small

#1937 Updated README to add my name and profile
  README.md
Labels: small

#1939 Update README.md
  README.md
Labels: small

#1944 Updated readme
  README.md
Labels: small

#1902 updated README: added name and github link
  README.md
Labels: small

#1904 Update README.md
  README.md
Labels: small

#1943 Added alok mahapatra
  README.md
Labels: small

#1974 add Kate Blake
  README.md
Labels: small

#1975 Add Sachin Kant to readme
  README.md
Labels: small

#1982 add Nicole Witherall to README.md
  README.md
Labels: small

#1920 Add Thrila
  README.md
Labels: small

#1983 Update README.md
  README.md
Labels: small

#1972 added my name to contributors
  README.md
Labels: small

#1988 Update Readme.md
  README.md
Labels: small

#1992 Update Readme.md
  README.md
Labels: small

#1995 Added my name to the list
  README.md
Labels: small

#1993 Updated README to add my name and profile
  README.md
Labels: small

#1998 Add zansangtan
  README.md
Labels: small

#1996 Update README
  README.md
Labels: small

#1997 Update README.md
  README.md
Labels: small

#2002 Update README to add my name
  README.md
Labels: small

#2003 Add Pooja Sharma in README.md
  README.md
Labels: small

#2001 Name Added to README.md
  README.md
Labels: small

#2008 Added my Name to the README
  README.md
Labels: small

#2009 Update README.md
  README.md
Labels: small

#2010 Added my name and Github link
  README.md
Labels: small

#2012 Update README.md
  README.md
Labels: small

#2011 Adding name to README.md
  README.md
Labels: small

#2004 Name Added to README.md
  README.md
Labels: small

#2015 Name add
  README.md
Labels: small

#1991 Updated Readme.md
  README.md
Labels: small

#2016 i added my name in h section
  README.md
Labels: small

#2021 Update: Updated my username in `README.md`
  README.md
Labels: small

#2019 add name
  README.md
Labels: small

#2018 Added my name
  README.md
Labels: small

#2022 Update README.md
  README.md
Labels: small

#2032 Add Name
  README.md
Labels: small

#2026 add iMuhammadessa to README.md
  README.md
Labels: small

#2034 Add devyanshiiii21
  README.md
Labels: small

#2027 Update README.md
  README.md
Labels: small

#2037 docs: fix grammatical mistakes in README.md
  README.md
Labels: large

#2041 Added my name.
  README.md
Labels: small

#2039 add tinniaru3005 to README.md
  README.md
Labels: small

#2035 jain changed a profile
  README.md
Labels: small

#2036 Update README.md
  README.md
Labels: small

#2040 Update README.md
  README.md
Labels: small

#2043 Add abhayhk2001
  README.md
Labels: small

#2044 add highfrezh
  README.md
Labels: small

#2046 add shreyam maity
  README.md
Labels: small

#2045 add my infos to readme
  README.md
Labels: small

#2048 haldarnup
  README.md
Labels: small

#1947 Update README.md
  README.md
Labels: small

#2049 added my name
  README.md
Labels: small

#2006 updating with minimising and less code in readme.
  README.md
Labels: medium

#2052 Update readme
  README.md
Labels: small

#2050 Add mohamedy72
  README.md
Labels: small

#2056 docs: minor update
  README.md
Labels: medium

#2055 Add Mithun-windows-linux
  README.md
Labels: small

#2038 Update README.md
  README.md
Labels: small

#2057 Add-my-name
  README.md
Labels: small

#2060 Add ShyamGadde
  README.md
Labels: small

#2061 Add ayush-3516
  README.md
Labels: small

#2065 Add RitikChourasiya
  README.md
Labels: small

#2066 Update README.md
  README.md
Labels: small

#2068 Add kanupriyabasoya
  README.md
Labels: small

#2064 fix: add Deepak
  README.md
Labels: small

#2054 Added Abhishek Anand
  README.md
Labels: small

#2062 Add Ramakm
  README.md
Labels: small

#2076 Added new name (Milena Brito)
  README.md
Labels: small

#2081 updated README.md folder with new name
  README.md
Labels: small

#2079 Added Sajal24
  README.md
Labels: small

#2086 Update README.md
  README.md
Labels: small

#2083 Added Name
  README.md
Labels: small

#2063 Update README.md
  README.md
Labels: small

#2085 Added my name AND RECTIFIED :)
  README.md
Labels: small

#2073 Updated
  README.md
Labels: small

#1718 Update README.md
  README.md
Labels: small

#2088 Add name to README.md
  README.md
Labels: small

#2091 bunde-uji
  README.md
Labels: small

#2089 Update README.md
  README.md
Labels: small

#2090 Update README.md
  README.md
Labels: small

#2096 Add VishwaS-22.md
  README.md
Labels: small

#2098 Add this-Aditya
  README.md
Labels: small

#2028 Name Added
  README.md
Labels: small

#2099 Update README.md
  README.md
Labels: small

#2107 Updated Readme.md
  README.md
Labels: small

#2095 Add Shashankzz0007
  README.md
Labels: small

#2108 addname
  README.md
Labels: small

#2070 Add my name
  README.md
Labels: small

#2111 Update README.md
  README.md
Labels: small

#2112 Updated README to add my name and profile
  README.md
Labels: small

#2113 Update README.md
  README.md
Labels: small

#2114 add Armel Munyaneza
  README.md
Labels: small

#2115 Updated the README file to add my name and profile
  README.md
Labels: small

#2117 chore: add Ikko Ashimine
  README.md
Labels: small

#2118 New branch
  README.md
Labels: small

#2119 Update README.md
  README.md
Labels: small

#2120 Add abdulsalam030
  README.md
Labels: small

#2116 Update README.md
  README.md
Labels: small

#2121 Added Ankit Singh & GitHub link
  README.md
Labels: small

#2122 Add plusted
  README.md
Labels: small

#2123 Update README.md
  README.md
Labels: small

#2124 Update README.md
  README.md
Labels: small

#2128 Added name in README.md
  README.md
Labels: small

#2126 Add Justinmemphis
  README.md
Labels: small

#2125 Added my name following alphabatical order in README.md
  README.md
Labels: small

#2131 updated readme.md
  README.md
Labels: small

#2129 Update README.md
  README.md
Labels: small

#2132 Supraja's Contribution
  README.md
Labels: small

#2134 Added my name
  README.md
Labels: small

#2135 Update README.md
  README.md
Labels: small

#2136 Update README.md
  README.md
Labels: small

#2137 Updated README.md to add my name and profile
  README.md
Labels: small

#2139 add name Sura Karthikeya
  README.md
Labels: small

#2141 Update README.md
  README.md
Labels: small

#2147 Update README.md
  README.md
Labels: small

#2146 Update README.md
  README.md
Labels: small

#2143 added: myName and link to my github profile
  README.md
Labels: small

#2148 Update README.md
  README.md
Labels: small
