Repository EddieHubCommunity/open-source-practice, pull requests merged in 2023-05, with the labels that each got.

#2752 feat/add-daniloparrajr-name
  README.md
Labels: small

#2706 Added Gaurav p
  README.md
Labels: small

#2769 Update README.md
  README.md
Labels: small

#2768 Added my name in alphabetically ordered list
  README.md
Labels: small

#2767 Add my name to README.MD
  README.md
Labels: small

#2765 Update README.md
  README.md
Labels: small

#2762 Added name/ first contribution
  README.md
Labels: small

#2763 Add https://github.com/Pyth0nHere
  README.md
Labels: small

#2760 name Eric-Obeng
  README.md
Labels: small

#2246 added some bold text, full stop and some other stuff.
  README.md
Labels: large

#2619 Name add
  README.md
Labels: small

#2754 Added my name to the readme.md
  README.md
Labels: small

#2778 Add myName to the readme
  README.md
Labels: small

#2773 MissZamzam
  README.md
Labels: small

#2775 added Poorvi J Nayak and github profile to README.md
  README.md
Labels: small

#2772 Add name to README file
  README.md
Labels: small

#2756 Adding my name to README.MD
  README.md
Labels: small

#2766 Added name to the list
  README.md
Labels: small

#2770 Added name
  README.md
Labels: small

#2782 Add Fatao
  README.md
Labels: small

#2788 Update README.md
  README.md
Labels: small

#2786 Add ayan878
  README.md
Labels: small

#2785 Add rep-pierce Fixed alphabetical error. My bad
  README.md
Labels: small

#2789 Add Aniketroy2003
  README.md
Labels: small

#2783 Update README.md
  README.md
Labels: small

#2792 Update README.md
  README.md
Labels: small

#2790 jalil dendane
  README.md
Labels: small, medium

#2794 Added my GitHub username to the project for workflow pratice
  README.md
Labels: small

#2781 data: sabrinalzbh
  README.md
Labels: small

#2796 Update README.md
  README.md
Labels: small

#2797 Add Lex Garey-Fernandez
  README.md
Labels: small

#2799 feature(new-name): added my name to the repo list
  README.md
Labels: medium

#2803 Added my name in README.md
  README.md
Labels: small

#2804 Add imranah10
  README.md
Labels: small

#2806 Added my name in README.md
  README.md
Labels: small

#2807 Add Abyss-Seeker
  README.md
Labels: small

#2808 Update README.md
  README.md
Labels: small

#2812 added my name.md
  README.md
Labels: small

#2813 Update README.md
  README.md
Labels: small

#2805 Update and rename README.md to README.mdBhaktiSharma
  README.md
Labels: small

#2815 Add name
  README.md
Labels: small

#2816 Update README.md
  README.md
Labels: small

#2811 Update README.md
  README.md
Labels: small

#2818 added Someshftw156
  README.md
Labels: small

#2817 chore: add Furkan Emin Can
  README.md
Labels: small

#2821 Update README.md
  README.md
Labels: small

#2820 Add Yash Kulkarni and Update README.md
  README.md
Labels: small

#2822 Update README.md
  README.md
Labels: small

#2823 Update README
  README.md
Labels: small

#2824 Added My Name
  README.md
Labels: small

#2825 Add raviraj-github
  README.md
Labels: small

#2830 add pranjaljaiswal10
  README.md
Labels: small

#2831 Adding my name Sahil Kaler
  README.md
Labels: small

#2834 Name add
  README.md
Labels: small

#2835 Update README.md
  README.md
Labels: small

#2826 Added My name
  README.md
Labels: small

#2836 Update README with aarpardev information
  README.md
Labels: small

#2833 state speciffically where to add name
  README.md
Labels: enhancement, small

#2837 Adding name to README.md
  README.md
Labels: small
